micronaut:
  application:
    name: flutter_api
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
  security:
    enabled: false
    authentication: session
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

graphql:
  enabled: true 
  path: /graphql
  graphiql:
    enabled: true
    path: /graphiql
